version: '3.3'
services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 4000:4000
            - 9229:9229
        networks:
            - nesjs-network
        depends_on:
            - mongodb
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network:
        driver: bridge
